import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarClock, CheckCircle2, CircleDashed, MapPin, UserRoundCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { MetricCard } from "@/components/ui/metric-card";
import { prisma } from "@/lib/prisma";
import { SERVICE_TYPE_LABEL } from "@/lib/reservations/service-type-labels";

function bahiaRange() {
  const date = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Bahia", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const start = new Date(`${date}T00:00:00-03:00`);
  const end = new Date(start); end.setUTCDate(end.getUTCDate() + 1);
  return { start, end };
}

const tone: Record<string, "success" | "info" | "warning" | "danger" | "neutral"> = { agendado: "neutral", em_andamento: "info", concluido: "success", cancelado: "danger" };
const label: Record<string, string> = { agendado: "Agendado", em_andamento: "Em andamento", concluido: "Concluído", cancelado: "Cancelado" };

export default async function ControlTowerPage() {
  const { start, end } = bahiaRange();
  const [services, pendingAcceptance, unassigned, overdue, openRequests] = await Promise.all([
    prisma.service.findMany({ where: { scheduled_date: { gte: start, lt: end }, execution_status: { not: "cancelado" } }, orderBy: [{ scheduled_time: "asc" }, { created_at: "asc" }], take: 80, select: { id: true, type: true, scheduled_time: true, execution_status: true, acceptance_status: true, pickup_location: true, dropoff_location: true, driver_id: true, vehicle_id: true, reservation: { select: { id: true, code: true, client: { select: { name: true } } } }, driver: { select: { name: true } }, vehicle: { select: { model: true, plate: true } } } }),
    prisma.service.count({ where: { execution_type: "fornecedor", acceptance_status: "aguardando_aceite", execution_status: "agendado" } }),
    prisma.service.count({ where: { scheduled_date: { gte: start, lt: end }, execution_status: "agendado", OR: [{ driver_id: null }, { vehicle_id: null }] } }),
    prisma.financeEntry.count({ where: { status: { in: ["programado", "pendente", "vencido"] }, due_date: { lt: new Date() }, reversed_at: null } }),
    prisma.changeRequest.count({ where: { status: { in: ["solicitada", "em_analise"] } } }),
  ]);
  const active = services.filter((service) => service.execution_status !== "concluido").length;
  return <div className="mx-auto max-w-[1480px] space-y-6">
    <header className="operational-strip p-4 sm:p-5"><p className="eyebrow">Operação em tempo real</p><div className="mt-1 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="page-heading">Torre de controle</h1><p className="page-description">Uma visão única do que está acontecendo hoje e do que precisa de ação.</p></div><span className="text-xs font-medium text-forest/60">{services.length} serviços programados hoje</span></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={CalendarClock} label="Em operação hoje" value={String(active)} accent="gold" /><MetricCard icon={CircleDashed} label="Aguardando aceite" value={String(pendingAcceptance)} accent={pendingAcceptance ? "warning" : "success"} /><MetricCard icon={UserRoundCheck} label="Sem alocação" value={String(unassigned)} accent={unassigned ? "danger" : "success"} /><MetricCard icon={AlertTriangle} label="Financeiro vencido" value={String(overdue)} accent={overdue ? "danger" : "success"} /></section>
    {(pendingAcceptance || unassigned || overdue || openRequests) > 0 && <section className="surface-panel p-4"><h2 className="section-heading">Ações prioritárias</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{pendingAcceptance > 0 && <Link href="/admin/reservas" className="interactive-panel flex items-center justify-between rounded-lg border border-warning/20 bg-warning-light px-3 py-3 text-sm text-warning">Aceitar serviços <ArrowRight size={16} /></Link>}{unassigned > 0 && <Link href="/admin/reservas" className="interactive-panel flex items-center justify-between rounded-lg border border-danger/20 bg-danger-light px-3 py-3 text-sm text-danger">Alocar recursos <ArrowRight size={16} /></Link>}{overdue > 0 && <Link href="/admin/financeiro?status=vencido" className="interactive-panel flex items-center justify-between rounded-lg border border-danger/20 bg-danger-light px-3 py-3 text-sm text-danger">Conferir vencidos <ArrowRight size={16} /></Link>}{openRequests > 0 && <Link href="/admin/solicitacoes" className="interactive-panel flex items-center justify-between rounded-lg border border-info/20 bg-info-light px-3 py-3 text-sm text-info">Ver solicitações <ArrowRight size={16} /></Link>}</div></section>}
    <section className="surface-panel overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-forest/10 px-4 py-4 sm:px-5"><div><h2 className="section-heading">Serviços de hoje</h2><p className="mt-1 text-xs text-forest/58">Acompanhe horário, rota e recurso em uma leitura operacional.</p></div><CheckCircle2 size={18} className="text-gold" /></div>{services.length === 0 ? <div className="p-10 text-center text-sm text-forest/60">Nenhum serviço programado para hoje.</div> : <ul className="divide-y divide-forest/[0.075]">{services.map((service) => <li key={service.id} className="p-4 sm:p-5"><div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div className="flex min-w-0 items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-forest/[0.06] text-xs font-semibold text-forest">{service.scheduled_time ?? "—"}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/admin/reservas/${service.reservation.id}?tab=servicos`} className="font-semibold text-forest underline decoration-gold/60 underline-offset-4">{service.reservation.code}</Link><Badge tone={tone[service.execution_status] ?? "neutral"}>{label[service.execution_status] ?? service.execution_status}</Badge>{service.acceptance_status !== "aceito" && <Badge tone="warning">Aceite pendente</Badge>}</div><p className="mt-1 truncate text-sm text-ink">{service.reservation.client.name}</p><p className="mt-1 flex min-w-0 items-center gap-1 text-xs text-forest/60"><MapPin size={13} className="shrink-0 text-gold" /> <span className="truncate">{service.pickup_location ?? "Origem não informada"} → {service.dropoff_location ?? "Destino não informado"}</span></p></div></div><div className="grid gap-1 text-xs text-forest/65 sm:grid-cols-2 lg:min-w-80 lg:grid-cols-2"><span><strong className="font-semibold text-forest">Serviço:</strong> {SERVICE_TYPE_LABEL[service.type]}</span><span><strong className="font-semibold text-forest">Motorista:</strong> {service.driver?.name ?? "Pendente"}</span><span><strong className="font-semibold text-forest">Veículo:</strong> {service.vehicle?.plate ?? "Pendente"}</span><span><strong className="font-semibold text-forest">Status:</strong> {service.execution_status === "em_andamento" ? "Em execução" : "Monitorar"}</span></div></div></li>)}</ul>}</section>
  </div>;
}
