import { afterAll, beforeEach, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));
vi.mock("next/navigation", () => ({ unstable_rethrow: vi.fn() }));
vi.mock("@/lib/auth/get-current-user", () => ({ assertActiveCompanyPortalUser: vi.fn(), requireOwnerUser: vi.fn(), requireFinancialUser: vi.fn(), requireInternalUser: vi.fn() }));
vi.mock("@/lib/uploads/payment-proof", () => ({ validatePaymentProof: vi.fn(async (value: string) => value) }));
vi.mock("@/lib/auth/provision-user", () => ({ provisionCompanyOrDriverLogin: vi.fn() }));
import { PrismaClient } from "@prisma/client";
import { assertActiveCompanyPortalUser, requireOwnerUser, requireFinancialUser, requireInternalUser } from "@/lib/auth/get-current-user";
import { provisionCompanyOrDriverLogin } from "@/lib/auth/provision-user";
import { requestSupplierDriverAccess, reportSupplierRemittance } from "@/app/portal/empresa/actions";
import { approveSupplierDriverAccess, confirmSupplierRemittance, updateChangeRequestStatus } from "@/app/admin/solicitacoes/actions";
import { generateServiceFinanceEntries, markServiceFinanceEntriesEligible } from "@/lib/finance/settlement";
import { confirmDirectCollectionReceived, ensureDirectSupplierRepasseRequest } from "@/lib/finance/direct-collection";
const prisma = new PrismaClient();
afterAll(() => prisma.$disconnect());
beforeEach(() => vi.clearAllMocks());
async function actors() {
  const company = await prisma.company.create({ data: { name: `Fornecedor ação ${crypto.randomUUID()}`, roles: ["fornecedor"], recebe_pagamento_direto: true } });
  const supplier = await prisma.user.create({ data: { auth_user_id: crypto.randomUUID(), email: `${crypto.randomUUID()}@teste.local`, account_type: "portal", linked_company_id: company.id } });
  const admin = await prisma.user.create({ data: { auth_user_id: crypto.randomUUID(), email: `${crypto.randomUUID()}@teste.local`, account_type: "internal", role: "admin", is_owner: true } });
  vi.mocked(assertActiveCompanyPortalUser).mockResolvedValue({ ...supplier, linked_company_id: company.id, linked_company: company, linked_driver: null });
  const internal = { ...admin, linked_company: null, linked_driver: null };
  vi.mocked(requireOwnerUser).mockResolvedValue(internal); vi.mocked(requireFinancialUser).mockResolvedValue(internal); vi.mocked(requireInternalUser).mockResolvedValue(internal);
  return { company, supplier, admin };
}
it("pedido de acesso fica pendente e só é concluído com criação e vínculo, sem contrato financeiro", async () => {
  const { company } = await actors();
  const driver = await prisma.driver.create({ data: { name: "Motorista solicita acesso", owner_type: "terceirizado", supplier_id: company.id, approval_status: "aprovado" } });
  const form = new FormData(); form.set("driver_id", driver.id); form.set("email", `${crypto.randomUUID()}@teste.local`); form.set("dedupe_key", crypto.randomUUID());
  expect((await requestSupplierDriverAccess({ error: null }, form)).error).toBeNull();
  const request = await prisma.changeRequest.findFirstOrThrow({ where: { company_id: company.id, type: "acesso_motorista" } });
  expect((await requestSupplierDriverAccess({ error: null }, form)).success).toContain(request.protocol);
  await expect(updateChangeRequestStatus(request.id, "aprovada", "")).rejects.toThrow("Aprovar e criar acesso");
  const portalUser = await prisma.user.create({ data: { auth_user_id: crypto.randomUUID(), email: String(form.get("email")), account_type: "portal", linked_driver_id: driver.id } });
  vi.mocked(provisionCompanyOrDriverLogin).mockResolvedValue({ created: false, user: portalUser });
  expect((await approveSupplierDriverAccess(request.id)).error).toBeNull();
  expect((await prisma.changeRequest.findUniqueOrThrow({ where: { id: request.id } })).status).toBe("concluida");
  expect((await prisma.driver.findUniqueOrThrow({ where: { id: driver.id } })).payment_type).toBeNull();
  expect(await prisma.auditLog.count({ where: { entity_id: request.id } })).toBe(2);
});
it("comprovante de repasse não baixa saldo até conferência; confirmação liga banco, data, protocolo e razão atomicamente", async () => {
  const { company, supplier } = await actors();
  const client = await prisma.client.create({ data: { name: "Passageiro fluxo completo" } });
  const reservation = await prisma.reservation.create({ data: { code: `FLUXO-${crypto.randomUUID()}`, client_id: client.id, collection_mode: "direto" } });
  const service = await prisma.service.create({ data: { reservation_id: reservation.id, type: "transfer_saida", execution_type: "fornecedor", supplier_id: company.id, supplier_cost: 300, price: 1000, original_price: 1000, collection_actor: "fornecedor", execution_status: "concluido", acceptance_status: "aceito" } });
  await generateServiceFinanceEntries(service.id); await markServiceFinanceEntriesEligible(service.id); await confirmDirectCollectionReceived(service.id);
  const originalRequest = await ensureDirectSupplierRepasseRequest(service.id, company.id);
  const entry = await prisma.financeEntry.findUniqueOrThrow({ where: { auto_key: `svc:${service.id}:repasse_fornecedor` } });
  const form = new FormData(); for (const [key, value] of Object.entries({ entry_id: entry.id, amount: "200", payment_date: "2020-01-01", payment_method: "pix", receipt_url: `storage://payment-receipts/${supplier.id}/${crypto.randomUUID()}.pdf`, dedupe_key: crypto.randomUUID() })) form.set(key, value);
  expect((await reportSupplierRemittance({ error: null }, form)).error).toBeNull();
  expect(await prisma.payment.count({ where: { finance_entry_id: entry.id } })).toBe(0);
  const request = await prisma.changeRequest.findFirstOrThrow({ where: { company_id: company.id, type: "pagamento_repasse_fornecedor" } });
  await expect(updateChangeRequestStatus(request.id, "aprovada", "")).rejects.toThrow("Confirmar recebimento");
  const bank = await prisma.bankAccount.create({ data: { name: "Conta teste repasse", type: "corrente" } });
  expect((await confirmSupplierRemittance(request.id, bank.id)).error).toBeNull();
  expect((await confirmSupplierRemittance(request.id, bank.id)).error).toBeNull();
  const payments = await prisma.payment.findMany({ where: { finance_entry_id: entry.id } }); expect(payments).toHaveLength(1);
  expect(payments[0].bank_account_id).toBe(bank.id); expect(payments[0].occurred_at?.toISOString()).toBe("2020-01-01T03:00:00.000Z");
  const reviewed = await prisma.changeRequest.findUniqueOrThrow({ where: { id: request.id } }); expect(reviewed.status).toBe("pago"); expect(reviewed.allocation_details).toMatchObject({ payment_id: payments[0].id, service_id: service.id });
  expect((await prisma.financeEntry.findUniqueOrThrow({ where: { id: entry.id } })).status).toBe("pendente");
  expect(await prisma.auditLog.count({ where: { entity_id: request.id, action: "repasse_fornecedor_confirmado" } })).toBe(1);
  if (!originalRequest) throw new Error("Protocolo automático ausente");
  await expect(updateChangeRequestStatus(originalRequest.id, "pago", "")).rejects.toThrow("Confirme primeiro");
  form.set("amount", "500"); form.set("dedupe_key", crypto.randomUUID());
  expect((await reportSupplierRemittance({ error: null }, form)).error).toBeNull();
  const secondRequest = await prisma.changeRequest.findFirstOrThrow({ where: { company_id: company.id, type: "pagamento_repasse_fornecedor", status: "solicitada" } });
  expect((await confirmSupplierRemittance(secondRequest.id, bank.id)).error).toBeNull();
  expect((await prisma.financeEntry.findUniqueOrThrow({ where: { id: entry.id } })).status).toBe("pago");
  expect((await prisma.changeRequest.findUniqueOrThrow({ where: { id: originalRequest.id } })).status).toBe("concluida");
});
it("nega aprovação sem proprietário e baixa sem financeiro antes de acessar o pedido", async () => {
  vi.mocked(requireOwnerUser).mockRejectedValue(new Error("Proprietário necessário"));
  vi.mocked(requireFinancialUser).mockRejectedValue(new Error("Financeiro necessário"));
  await expect(approveSupplierDriverAccess(crypto.randomUUID())).rejects.toThrow("Proprietário");
  await expect(confirmSupplierRemittance(crypto.randomUUID(), crypto.randomUUID())).rejects.toThrow("Financeiro");
});
