"use client";
import { useState, useTransition } from "react";
import { approveSupplierDriverAccess, confirmSupplierRemittance } from "@/app/admin/solicitacoes/actions";
import { buttonClass, inputClass } from "@/lib/ui";
export function SupplierRequestActions({ id, type, status, bankAccounts }: { id: string; type: string; status: string; bankAccounts: { id: string; name: string }[] }) {
  const [pending, start] = useTransition(); const [error, setError] = useState<string | null>(null); const [credentials, setCredentials] = useState<{ email: string | null; temporaryPassword: string | null } | null>(null); const [bank, setBank] = useState(""); const [done, setDone] = useState(false);
  if (credentials) return <div className="rounded-lg border border-success/25 p-3 text-sm"><p>Acesso criado: {credentials.email}</p>{credentials.temporaryPassword && <><p className="mt-2">Senha temporária: <strong className="break-all">{credentials.temporaryPassword}</strong></p><p className="mt-2 text-xs">Entregue ao motorista por um canal privado. Ele deverá trocar a senha no primeiro acesso. A senha não fica no protocolo do fornecedor.</p></>}</div>;
  if (["rejeitada", "concluida", "pago"].includes(status) || done) return done ? <p role="status" className="text-sm text-success">Recebimento confirmado no financeiro.</p> : null;
  return <div className="mb-4 grid gap-2">{type === "pagamento_repasse_fornecedor" && <><a href={`/api/portal/comprovantes/${id}`} target="_blank" rel="noopener noreferrer" className="text-sm font-semibold underline">Conferir comprovante</a><label className="grid gap-1 text-xs">Conta da Nativos que recebeu<select value={bank} onChange={e => setBank(e.target.value)} className={inputClass}><option value="">Selecione a conta</option>{bankAccounts.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><p className="text-xs text-forest/65">Confirme somente após conferir o crédito real na conta. O recebimento será vinculado ao serviço e à reserva.</p></>}
    <button disabled={pending || (type === "pagamento_repasse_fornecedor" && !bank)} className={buttonClass} onClick={() => start(async () => { setError(null); try { if (type === "acesso_motorista") { const result = await approveSupplierDriverAccess(id); if (result.error) setError(result.error); else setCredentials(result); } else { const result = await confirmSupplierRemittance(id, bank); if (result.error) setError(result.error); else setDone(true); } } catch { setError("Não foi possível concluir. Verifique sua permissão e tente novamente."); } })}>{pending ? "Confirmando..." : type === "acesso_motorista" ? "Aprovar e criar acesso" : "Confirmar recebimento"}</button>{error && <p role="alert" className="text-sm text-danger">{error}</p>}
  </div>;
}
