"use client";
import { useActionState } from "react";
import { updateCompanySettings } from "./actions";
import { buttonClass, inputClass, labelClass } from "@/lib/ui";
const initial = { error: null, saved: false };
export function CompanySettingsForm({ defaults }: { defaults: Record<string, string> }) {
  const [state, action, pending] = useActionState(updateCompanySettings, initial);
  return <form action={action} className="surface-panel grid max-w-3xl gap-4 p-5 md:grid-cols-2"><label className="md:col-span-2"><span className={labelClass}>Razão/nome comercial *</span><input name="name" required defaultValue={defaults.name ?? "Nativos Experiences"} className={inputClass} /></label><label><span className={labelClass}>CNPJ/CPF</span><input name="document" defaultValue={defaults.document ?? ""} className={inputClass} /></label><label><span className={labelClass}>Telefone/WhatsApp</span><input name="phone" defaultValue={defaults.phone ?? ""} className={inputClass} /></label><label><span className={labelClass}>E-mail</span><input name="email" type="email" defaultValue={defaults.email ?? ""} className={inputClass} /></label><label><span className={labelClass}>Site</span><input name="website" type="url" defaultValue={defaults.website ?? ""} className={inputClass} /><p className="mt-1 text-[11px] text-forest/45">Informe com https://</p></label><label className="md:col-span-2"><span className={labelClass}>Endereço</span><input name="address" defaultValue={defaults.address ?? ""} className={inputClass} /></label><label><span className={labelClass}>Cidade</span><input name="city" defaultValue={defaults.city ?? "Trancoso"} className={inputClass} /></label><label><span className={labelClass}>UF</span><input name="state" maxLength={2} defaultValue={defaults.state ?? "BA"} className={inputClass} /></label><label className="md:col-span-2"><span className={labelClass}>Rodapé dos documentos</span><textarea name="footer" rows={3} defaultValue={defaults.footer ?? ""} className={inputClass} /></label>{state.error && <p className="text-sm text-red-700 md:col-span-2">{state.error}</p>}{state.saved && <p className="text-sm text-success md:col-span-2">Dados salvos.</p>}<button disabled={pending} className={`${buttonClass} md:col-span-2`}>{pending ? "Salvando…" : "Salvar dados da empresa"}</button></form>;
}
